[2023-03-27T03:24:16.121+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: projeto_agro.extract_data manual__2023-03-27T03:24:12.809639+00:00 [queued]>
[2023-03-27T03:24:16.136+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: projeto_agro.extract_data manual__2023-03-27T03:24:12.809639+00:00 [queued]>
[2023-03-27T03:24:16.137+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T03:24:16.137+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-03-27T03:24:16.137+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T03:24:16.161+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_data> on 2023-03-27 03:24:12.809639+00:00
[2023-03-27T03:24:16.168+0000] {standard_task_runner.py:55} INFO - Started process 277 to run task
[2023-03-27T03:24:16.171+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'projeto_agro', 'extract_data', 'manual__2023-03-27T03:24:12.809639+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp9cx60s7g']
[2023-03-27T03:24:16.172+0000] {standard_task_runner.py:83} INFO - Job 92: Subtask extract_data
[2023-03-27T03:24:16.269+0000] {task_command.py:389} INFO - Running <TaskInstance: projeto_agro.extract_data manual__2023-03-27T03:24:12.809639+00:00 [running]> on host 264f1e537a4a
[2023-03-27T03:24:16.485+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=projeto_agro
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T03:24:12.809639+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-27T03:24:12.809639+00:00
[2023-03-27T03:24:33.638+0000] {logging_mixin.py:137} WARNING - /opt/airflow/dags/../../scripts/extract.py:32 DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
[2023-03-27T03:24:33.807+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 15, in extract
    extract = Extract()
  File "/opt/airflow/dags/../../scripts/extract.py", line 15, in __init__
    service_account.Credentials.from_service_account_file(
  File "/usr/local/lib/python3.9/site-packages/google/oauth2/service_account.py", line 241, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/usr/local/lib/python3.9/site-packages/google/auth/_service_account_info.py", line 80, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/credentials/zoomcamp-374100-a34bc7914122.json'
[2023-03-27T03:24:33.823+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=projeto_agro, task_id=extract_data, execution_date=20230327T032412, start_date=20230327T032416, end_date=20230327T032433
[2023-03-27T03:24:33.843+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 92 for task extract_data ([Errno 2] No such file or directory: '/opt/credentials/zoomcamp-374100-a34bc7914122.json'; 277)
[2023-03-27T03:24:33.899+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-27T03:24:33.928+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
